name: Run Hello world from Python Script
on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'

      - name: Run Python script
        run: python hello.py